### ISSUE TITLE
Setup a Vector3 type

### ISSUE THREAD

**Issue by angered-ghandi** [angered-ghandi/OpenAOE#18]
We'll need a Vector3 object in the types crate for unit positions and movement math. This should have the usual (x, y, z) coordinates, operator overloading for add/subtract/scale, and length/normalize methods.

We can use the [nalgebra](https://github.com/sebcrozet/nalgebra) library for this, though we should probably re-export their types through our type crate with generic types already specified.

**Comment by Xinayder** [comment]
I timed `cargo build` and seems like using nalgebra only adds 5 seconds to compile time. I used `cargo build --release` and then `time cargo build` to time it.

Results:
- Without nalgebra: `real    1m2.329s`
- With nalgebra: `real    1m7.788s`

```
Jul 13 18:31:20 <Xinayder>  I was thinking of implementing the vector3 type
Jul 13 18:31:42 <Xinayder>  I read what you and kevin said about nalgebra
Jul 13 18:32:00 <Phrohdoh>  There is no reason to handroll basic structures like that imo.
Jul 13 18:32:13 <Xinayder>  importing from nalgebra is much more work than doing it manually
Jul 13 18:32:24 <Phrohdoh>  except it isn't
Jul 13 18:32:38 <Phrohdoh>  extern crate nalgebra; use nalgebra::Vector3; done
Jul 13 18:32:43 <Phrohdoh>  or vec3, whatever
Jul 13 18:32:56 <Xinayder>  that's the problem
Jul 13 18:33:32 <Xinayder>  you are literally depending on the whole crate just to use a single type
Jul 13 18:33:46 <Phrohdoh>  We'll end up using more is my point.
```

I'd say it's worth the try depending on `nalgebra`, as like @Phrohdoh said we'd end up using more types from the crate, instead of only using `Vector3`.

**Comment by angered-ghandi** [comment]
Let's use `nalgebra`.
