### ISSUE TITLE
error: failed to run custom build command for `miniz-sys v0.1.7`

### ISSUE THREAD

**Issue by CptZeroVoltz** [angered-ghandi/OpenAOE#5]
When I tried to build the latest code base it failed with the following error

> `Build failed, waiting for other jobs to finish...
> error: failed to run custom build command for`miniz-sys v0.1.7`
> Process didn't exit successfully:`C:\Users\Sigma2\Desktop\openaoe\target\releas
> e\build\miniz-sys-60c8d67696f63a43\build-script-build` (exit code: 101)
> --- stdout
> TARGET = Some("x86_64-pc-windows-gnu")
> OPT_LEVEL = Some("3")
> PROFILE = Some("release")
> TARGET = Some("x86_64-pc-windows-gnu")
> debug=false opt-level=3
> HOST = Some("x86_64-pc-windows-gnu")
> TARGET = Some("x86_64-pc-windows-gnu")
> TARGET = Some("x86_64-pc-windows-gnu")
> HOST = Some("x86_64-pc-windows-gnu")
> CC_x86_64-pc-windows-gnu = None
> CC_x86_64_pc_windows_gnu = None
> HOST_CC = None
> CC = None
> TARGET = Some("x86_64-pc-windows-gnu")
> HOST = Some("x86_64-pc-windows-gnu")
> CFLAGS_x86_64-pc-windows-gnu = None
> CFLAGS_x86_64_pc_windows_gnu = None
> HOST_CFLAGS = None
> CFLAGS = None
> running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-o" "C:
> \Users\Sigma2\Desktop\openaoe\target\release\build\miniz-sys-60c8d67696f
> 63a43\out\miniz.o" "-c" "miniz.c"
> 
> failed to execute command: The system cannot find the file specified. (os error
> 2)
> Is `gcc.exe` not installed? (see https://github.com/alexcrichton/gcc-rs#compile-
> time-requirements for help)
> 
> --- stderr
> thread '<main>' panicked at 'explicit panic', C:\Users\Sigma2.cargo\registry\sr
> c\github.com-1ecc6299db9ec823\gcc-0.3.28\src\lib.rs:840
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 
> `

Running windows 7 x64

**Comment by angered-ghandi** [comment]
It's failing because it can't find gcc on the PATH. It needs gcc to compile miniz (a smaller version of zlib) for decompressing some of the AOE files. You have two options:
1. Make sure gcc (via MINGW) is installed and on your PATH, or
2. Install Visual C++ and ensure that cl.exe is on your PATH; there's probably some other stuff you have to do to tell cargo to build with MSVC instead of MINGW in this instance, but I'm not familiar with the process.

Both options are described here:
https://github.com/alexcrichton/gcc-rs#compile-time-requirements

Edit: Markdown renumbering everything as one... that was amusing.

**Comment by angered-ghandi** [comment]
Looks like I forgot to update the readme after adding several dependencies that make the build less trivial. I added some more details to it, but I don't have a Windows machine with me at the moment. If you do get it working, it'd be amazing if you could write up some instructions.

Thanks for giving it a try, btw!

**Comment by angered-ghandi** [comment]
@RockyTV contributed some Windows build instructions. I'm going to close this issue for now. Go ahead and re-open if you run into more trouble.
